import fs from 'fs/promises'
import path from 'path'
import os from 'os'
import { getConfig } from './config'
import type { Message, NoteMetadata, NoteContent } from '@/types'

export function sanitizeTheme(theme: string): string {
  return (
    theme
      .trim()
      .replace(/[/\\:*?"<>|\n\r]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '')
      .slice(0, 40) || 'untitled'
  )
}

export function buildFileName(theme: string, startedAt: Date): string {
  const d = startedAt
  const pad = (n: number) => String(n).padStart(2, '0')
  const date = `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}`
  const time = `${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`
  return `${date}_${time}_${sanitizeTheme(theme)}.md`
}

export function buildMarkdown(params: {
  theme: string
  messages: Message[]
  model: string
  startedAt: Date
  summary: string
  surfaced: string[]
}): string {
  const { theme, messages, model, startedAt, summary, surfaced } = params
  const turns = messages.filter(m => m.role === 'user').length

  const frontmatter = [
    '---',
    `date: ${startedAt.toISOString()}`,
    `theme: ${theme}`,
    `model: ${model}`,
    `turns: ${turns}`,
    '---',
  ].join('\n')

  const surfacedSection =
    surfaced.length > 0 ? surfaced.map(s => `- ${s}`).join('\n') : '_（なし）_'

  const dialogueLog = messages
    .map(m => {
      const label = m.role === 'user' ? '**You:**' : '**Diguest:**'
      return `${label}\n\n${m.content}`
    })
    .join('\n\n---\n\n')

  return [
    frontmatter,
    '',
    `# ${theme}`,
    '',
    '## 対話の要約',
    '',
    summary || '_（生成できませんでした）_',
    '',
    '## 掘り出されたもの',
    '',
    surfacedSection,
    '',
    '## 対話ログ',
    '',
    dialogueLog,
    '',
    '---',
    '_Generated by Diguest_',
  ].join('\n')
}

function resolvedNotesDir(): string {
  const { notesDir } = getConfig()
  return expandHome(notesDir)
}

function expandHome(dir: string): string {
  if (dir.startsWith('~/') || dir === '~') {
    return path.join(os.homedir(), dir.slice(1))
  }
  return dir
}

function guardPath(fileName: string, dir: string): string {
  const safeName = path.basename(fileName)
  if (!safeName.endsWith('.md')) throw new Error('Invalid file name')
  const resolvedDir = path.resolve(dir)
  const filePath = path.resolve(path.join(resolvedDir, safeName))
  if (!filePath.startsWith(resolvedDir + path.sep)) throw new Error('Invalid file path')
  return filePath
}

export async function saveNote(
  markdown: string,
  fileName: string,
  saveDir?: string,
): Promise<{ filePath: string; fileName: string }> {
  const dir = saveDir ? expandHome(saveDir) : resolvedNotesDir()
  const resolvedDir = path.resolve(dir)
  await fs.mkdir(resolvedDir, { recursive: true })

  const safeName = path.basename(fileName)
  if (!safeName.endsWith('.md')) throw new Error('Invalid file name')

  const base = safeName.slice(0, -3)
  let candidate = safeName
  let counter = 2

  while (true) {
    const filePath = path.resolve(path.join(resolvedDir, candidate))
    if (!filePath.startsWith(resolvedDir + path.sep)) throw new Error('Invalid file path')
    try {
      await fs.access(filePath)
      candidate = `${base}-${counter}.md`
      counter++
    } catch {
      await fs.writeFile(filePath, markdown, 'utf-8')
      return { filePath, fileName: candidate }
    }
  }
}

export async function listNotes(): Promise<NoteMetadata[]> {
  const dir = resolvedNotesDir()
  try {
    const files = await fs.readdir(dir)
    const results = await Promise.allSettled(
      files
        .filter(f => f.endsWith('.md') && f !== 'config.json')
        .map(async fileName => {
          const content = await fs.readFile(path.join(dir, fileName), 'utf-8')
          return parseFrontmatter(content, fileName)
        })
    )
    return results
      .filter(
        (r): r is PromiseFulfilledResult<NoteMetadata> =>
          r.status === 'fulfilled' && r.value !== null
      )
      .map(r => r.value)
      .sort((a, b) => b.date.localeCompare(a.date))
  } catch {
    return []
  }
}

export async function readNote(fileName: string): Promise<NoteContent | null> {
  const dir = resolvedNotesDir()
  let filePath: string
  try {
    filePath = guardPath(fileName, dir)
  } catch {
    return null
  }
  try {
    const rawMarkdown = await fs.readFile(filePath, 'utf-8')
    const metadata = parseFrontmatter(rawMarkdown, path.basename(fileName))
    if (!metadata) return null
    return { metadata, rawMarkdown }
  } catch {
    return null
  }
}

function parseFrontmatter(content: string, fileName: string): NoteMetadata | null {
  const match = content.match(/^---\n([\s\S]*?)\n---/)
  if (!match) return null
  const fm = match[1]
  const get = (key: string): string => {
    const m = fm.match(new RegExp(`^${key}:\\s*(.+)$`, 'm'))
    return m?.[1]?.trim() ?? ''
  }
  return {
    fileName,
    theme: get('theme'),
    date: get('date'),
    model: get('model'),
    turns: parseInt(get('turns') || '0', 10),
  }
}
