import Foundation

struct NoteStore {
    private let fileManager = FileManager.default

    func notesDirectory(config: AppConfig) -> URL {
        expandHome(config.notesDir)
    }

    func buildFileName(theme: String, startedAt: Date) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyyMMdd_HHmmss"
        return "\(formatter.string(from: startedAt))_\(sanitizeTheme(theme)).md"
    }

    func buildMarkdown(
        theme: String,
        messages: [Message],
        model: String,
        startedAt: Date,
        summary: String,
        surfaced: [String]
    ) -> String {
        let turns = messages.filter { $0.role == .user }.count
        let isoDate = ISO8601DateFormatter().string(from: startedAt)
        let surfacedSection = surfaced.isEmpty ? "_（なし）_" : surfaced.map { "- \($0)" }.joined(separator: "\n")
        let dialogueLog = messages
            .filter { $0.role != .system }
            .map { message in
                let label = message.role == .user ? "**You:**" : "**Diguest:**"
                return "\(label)\n\n\(message.content)"
            }
            .joined(separator: "\n\n---\n\n")

        return [
            "---",
            "date: \(isoDate)",
            "theme: \(theme)",
            "model: \(model)",
            "turns: \(turns)",
            "---",
            "",
            "# \(theme)",
            "",
            "## 対話の要約",
            "",
            summary.isEmpty ? "_（生成できませんでした）_" : summary,
            "",
            "## 掘り出されたもの",
            "",
            surfacedSection,
            "",
            "## 対話ログ",
            "",
            dialogueLog,
            "",
            "---",
            "_Generated by Diguest_"
        ].joined(separator: "\n")
    }

    func save(markdown: String, fileName: String, config: AppConfig) throws -> String {
        let dir = notesDirectory(config: config)
        try fileManager.createDirectory(at: dir, withIntermediateDirectories: true)

        let safeName = URL(fileURLWithPath: fileName).lastPathComponent
        guard safeName.hasSuffix(".md") else {
            throw CocoaError(.fileWriteInvalidFileName)
        }

        let base = String(safeName.dropLast(3))
        var candidate = safeName
        var counter = 2

        while true {
            let fileURL = dir.appendingPathComponent(candidate)
            if !fileManager.fileExists(atPath: fileURL.path) {
                try markdown.write(to: fileURL, atomically: true, encoding: .utf8)
                return candidate
            }

            candidate = "\(base)-\(counter).md"
            counter += 1
        }
    }

    func listNotes(config: AppConfig) -> [NoteMetadata] {
        let dir = notesDirectory(config: config)
        guard let files = try? fileManager.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil) else {
            return []
        }

        return files
            .filter { $0.pathExtension == "md" }
            .compactMap { url in
                guard let content = try? String(contentsOf: url, encoding: .utf8) else { return nil }
                return parseFrontmatter(content: content, fileName: url.lastPathComponent)
            }
            .sorted { $0.date > $1.date }
    }

    func read(fileName: String, config: AppConfig) -> NoteContent? {
        let safeName = URL(fileURLWithPath: fileName).lastPathComponent
        let fileURL = notesDirectory(config: config).appendingPathComponent(safeName)
        guard
            let rawMarkdown = try? String(contentsOf: fileURL, encoding: .utf8),
            let metadata = parseFrontmatter(content: rawMarkdown, fileName: safeName)
        else {
            return nil
        }

        return NoteContent(metadata: metadata, rawMarkdown: rawMarkdown)
    }

    private func sanitizeTheme(_ theme: String) -> String {
        let invalid = CharacterSet(charactersIn: "/\\\\:*?\"<>|\n\r")
        let cleaned = theme
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .components(separatedBy: invalid)
            .joined(separator: "_")
            .replacingOccurrences(of: "_+", with: "_", options: .regularExpression)
            .trimmingCharacters(in: CharacterSet(charactersIn: "_"))

        let limited = String(cleaned.prefix(40))
        return limited.isEmpty ? "untitled" : limited
    }

    private func expandHome(_ path: String) -> URL {
        if path == "~" {
            return fileManager.homeDirectoryForCurrentUser
        }

        if path.hasPrefix("~/") {
            return fileManager.homeDirectoryForCurrentUser.appendingPathComponent(String(path.dropFirst(2)))
        }

        return URL(fileURLWithPath: path)
    }

    private func parseFrontmatter(content: String, fileName: String) -> NoteMetadata? {
        guard content.hasPrefix("---") else { return nil }
        let parts = content.components(separatedBy: "\n---")
        guard let frontmatter = parts.first else { return nil }

        func value(_ key: String) -> String {
            frontmatter
                .components(separatedBy: "\n")
                .first { $0.hasPrefix("\(key):") }?
                .dropFirst(key.count + 1)
                .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        }

        return NoteMetadata(
            fileName: fileName,
            theme: value("theme"),
            date: value("date"),
            model: value("model"),
            turns: Int(value("turns")) ?? 0
        )
    }
}

