import XCTest
@testable import Diguest

final class ResumeSnapshotTests: XCTestCase {
    func testEncodeAndDecodeRoundTripPreservesTurnsAndAnswers() {
        let turns: [ChoiceTurn] = [
            ChoiceTurn(
                question: "それは内側からの違和感？",
                options: [
                    ChoiceOption(index: 1, text: "内側からだと思う"),
                    ChoiceOption(index: 2, text: "外からの違和感だ"),
                    ChoiceOption(index: 3, text: "両方ある"),
                    ChoiceOption(index: 4, text: "近いものがないので書く", isFreeWrite: true)
                ],
                rawAssistantText: "",
                answer: .selected(index: 2, text: "外からの違和感だ")
            ),
            ChoiceTurn(
                question: "外の何が違和感を呼ぶ？",
                options: [
                    ChoiceOption(index: 1, text: "人の言葉"),
                    ChoiceOption(index: 2, text: "場の空気"),
                    ChoiceOption(index: 3, text: "音や匂い"),
                    ChoiceOption(index: 4, text: "近いものがないので書く", isFreeWrite: true)
                ],
                rawAssistantText: "",
                answer: .edited(originalIndex: 1, originalText: "人の言葉", editedText: "誰かの態度")
            ),
            ChoiceTurn(
                question: "態度のどこに引っかかった？",
                options: [
                    ChoiceOption(index: 1, text: "言い方"),
                    ChoiceOption(index: 2, text: "目線"),
                    ChoiceOption(index: 3, text: "間"),
                    ChoiceOption(index: 4, text: "近いものがないので書く", isFreeWrite: true)
                ],
                rawAssistantText: "",
                answer: .freeWritten("言ってないのに伝わってる感じ\nがあった"),
                isFallback: true
            ),
            // 最後のターンは未回答（保存時の典型ケース）
            ChoiceTurn(
                question: "その感じは、いつから？",
                options: [
                    ChoiceOption(index: 1, text: "今日から"),
                    ChoiceOption(index: 2, text: "数日前から"),
                    ChoiceOption(index: 3, text: "もっと前から"),
                    ChoiceOption(index: 4, text: "近いものがないので書く", isFreeWrite: true)
                ],
                rawAssistantText: "",
                answer: nil
            )
        ]

        let snapshot = ResumeSnapshotEncoder.make(
            seedText: "最近、人と話したあと違和感が残る",
            choiceTurns: turns,
            depthLevel: 4
        )

        guard let block = ResumeSnapshotEncoder.encodeBlock(snapshot) else {
            XCTFail("encodeBlock returned nil")
            return
        }

        let markdown = """
        ---
        date: "..."
        ---
        # テーマ

        本文...

        \(block)
        """

        guard let decoded = ResumeSnapshotEncoder.decodeBlock(from: markdown) else {
            XCTFail("decodeBlock returned nil")
            return
        }

        XCTAssertEqual(decoded.v, 1)
        XCTAssertEqual(decoded.depth, 4)
        XCTAssertEqual(decoded.seed, "最近、人と話したあと違和感が残る")
        XCTAssertEqual(decoded.turns.count, 4)

        let restored = ResumeSnapshotDecoder.choiceTurns(from: decoded)
        XCTAssertEqual(restored.count, 4)

        XCTAssertEqual(restored[0].question, "それは内側からの違和感？")
        XCTAssertEqual(restored[0].options.count, 4)
        XCTAssertTrue(restored[0].options[3].isFreeWrite)
        if case let .selected(index, text) = restored[0].answer {
            XCTAssertEqual(index, 2)
            XCTAssertEqual(text, "外からの違和感だ")
        } else {
            XCTFail("expected selected answer")
        }

        if case let .edited(originalIndex, originalText, editedText) = restored[1].answer {
            XCTAssertEqual(originalIndex, 1)
            XCTAssertEqual(originalText, "人の言葉")
            XCTAssertEqual(editedText, "誰かの態度")
        } else {
            XCTFail("expected edited answer")
        }

        XCTAssertTrue(restored[2].isFallback)
        if case let .freeWritten(text) = restored[2].answer {
            XCTAssertEqual(text, "言ってないのに伝わってる感じ\nがあった")
        } else {
            XCTFail("expected freeWritten answer")
        }

        XCTAssertNil(restored[3].answer, "最後のターンは未回答")
    }

    func testStripBlockRemovesResumeCommentAndTrailingWhitespace() {
        let markdown = """
        # テーマ

        本文の内容

        ---
        _Generated by Diguest_

        <!-- diguest-resume: {"v":1,"depth":2,"seed":"...","turns":[]} -->
        """

        let stripped = ResumeSnapshotEncoder.stripBlock(from: markdown)
        XCTAssertFalse(stripped.contains("diguest-resume"))
        XCTAssertFalse(stripped.contains("<!--"))
        XCTAssertTrue(stripped.hasSuffix("_Generated by Diguest_"))
    }

    func testDecodeBlockReturnsNilForLegacyMarkdownWithoutSnapshot() {
        let legacy = """
        ---
        date: "2025-12-01"
        theme: "古い掘り跡"
        ---
        # 古い掘り跡

        本文
        """

        XCTAssertNil(ResumeSnapshotEncoder.decodeBlock(from: legacy))
        XCTAssertEqual(ResumeSnapshotEncoder.stripBlock(from: legacy), legacy)
    }
}
